"""Alert models."""

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


class AlertLevel(str, Enum):
    info = "info"
    warning = "warning"
    breach = "breach"
    escape = "escape"


class AlertType(str, Enum):
    boundary_approach = "boundary_approach"
    geofence_breach = "geofence_breach"
    escape_detected = "escape_detected"
    signal_lost = "signal_lost"
    return_detected = "return_detected"


class Alert(BaseModel, frozen=True):
    """An alert generated by the detection engine."""

    id: str = Field(description="Unique alert identifier")
    dog_id: str
    device_id: str
    type: AlertType
    level: AlertLevel
    geofence_id: str | None = Field(default=None)
    message: str = Field(default="")
    lat: float | None = Field(default=None)
    lon: float | None = Field(default=None)
    acknowledged: bool = Field(default=False)
    created_at: datetime = Field(default_factory=datetime.utcnow)
